#if !defined(__SCADA_RIGHT_DEFINE_H_)
#define __SCADA_RIGHT_DEFINE_H_


#define CURRENT_MAX_RIGHT	89
#define	RIGHT_ALARM_ACK     		  17	//一般报警确认
#define	RIGHT_ALARM_CLEAR   		  19	//一般报警清除
#define	RIGHT_ALARM_CONFIG  		  18	//报警配置
#define	RIGHT_ALARM_MANAGER 		  64	//历史报警维护
#define	RIGHT_ALARM_R       		   6	//启动报警
#define	RIGHT_ALARM_RIGHTACK		  43	//授权报警确认
#define	RIGHT_ALARM_RTCLEAR 		  44	//授权报警清除
#define	RIGHT_ALARM_S       		  55	//停止报警
#define	RIGHT_CA_CONTROL    		  74	//CA参数配置
#define	RIGHT_CA_RUN        		  75	//CA运行
#define	RIGHT_CURVE_CONFIG  		  50	//曲线配置
#define	RIGHT_CURVE_RS      		  11	//启停曲线
#define	RIGHT_DBDUMP_CONFIG 		  35	//数据管理配置
#define	RIGHT_DBDUMP_EXPORT 		  33	//数据备份
#define	RIGHT_DBDUMP_IMPORT 		  34	//数据回装
#define	RIGHT_DBDUMP_RS     		  12	//启停数据管理
#define	RIGHT_DTS_CTRL      		   3	//DTS控制
#define	RIGHT_DZOPER_CALL   		  58	//工程师站召唤操作
#define	RIGHT_DZOPER_CONFIG 		  86	//工程师站系统配置
#define	RIGHT_DZOPER_EDIT   		  59	//定值报表编辑
#define	RIGHT_DZOPER_PRINT  		  60	//定值报表打印
#define	RIGHT_DZOPER_RS     		  16	//启停工程师站
#define	RIGHT_DZOPER_YK     		  85	//工程师站控制操作
#define	RIGHT_EDIT_DTS      		  69	//DTS库维护
#define	RIGHT_EDIT_NET      		  31	//NET库维护
#define	RIGHT_EDIT_NETNODE  		  29	//网络维护
#define	RIGHT_EDIT_PROCESS  		  48	//进程管理
#define	RIGHT_EDIT_SCADA    		  30	//SCADA库维护
#define	RIGHT_EDIT_SRS      		  49	//SRS库维护
#define	RIGHT_EDIT_SYSTEM   		  61	//系统库维护
#define	RIGHT_EDIT_TOPO     		  32	//TOPO库维护
#define	RIGHT_EDIT_USER     		  28	//用户定义
#define	RIGHT_FAULTREC_RS   		  15	//启停故障录波
#define	RIGHT_FAULTREC_SERVE		  53	//启停故障录波服务
#define	RIGHT_GOTO_OS       		  57	//返回操作系统
#define	RIGHT_HIDE_FIELD_SET		  63	//配置可查看列
#define	RIGHT_HISTORY_RS    		   9	//启停历史存储
#define	RIGHT_HISTORY_SERVER		  52	//启停历史转储服务
#define	RIGHT_HIS_DATAEDIT  		  65	//历史数据维护
#define	RIGHT_LOGVIEW_RS    		  13	//启停日志
#define	RIGHT_MMIEDIT_RS    		   5	//启停图形编辑
#define	RIGHT_MMI_CARD      		  24	//挂牌
#define	RIGHT_MMI_COMPONENT 		  26	//图元编辑
#define	RIGHT_MMI_CUSTOM    		  45	//图形操作习惯配置
#define	RIGHT_MMI_DEVMAN    		  62	//设备管理
#define	RIGHT_MMI_EDIT      		  25	//图形编辑
#define	RIGHT_MMI_IMPORTRC  		  56	//重要遥控
#define	RIGHT_MMI_LOOK      		  47	//调度监护
#define	RIGHT_MMI_MASK      		  23	//屏蔽
#define	RIGHT_MMI_R         		   4	//启动图形监视
#define	RIGHT_MMI_RCEDIT    		  46	//顺控编辑
#define	RIGHT_MMI_RCRIGHT   		  27	//设备授权
#define	RIGHT_MMI_S         		  54	//停止图形监视
#define	RIGHT_MMI_SERIALRC  		  21	//顺控
#define	RIGHT_MMI_SETVALUE  		  22	//置数
#define	RIGHT_MMI_SINGLERC  		  20	//单控
#define	RIGHT_MMI_SOFTJUDGE 		  42	//闭锁设置
#define	RIGHT_PDR_RS        		  14	//启停事故追忆
#define	RIGHT_PF_CONTROL    		  72	//PF参数配置
#define	RIGHT_PF_RUN        		  73	//PF运行
#define	RIGHT_PLD_EDIT      		  87	//旁路代编辑
#define	RIGHT_PLD_OPR       		  88	//旁路代操作
#define	RIGHT_RC_TEST       		  51	//检修遥控
#define	RIGHT_REPORT_EDIT   		  40	//报表编辑
#define	RIGHT_REPORT_FILL   		  66	//修改当日报表数据
#define	RIGHT_REPORT_PRINT  		  41	//报表打印
#define	RIGHT_REPORT_RS     		  10	//启停报表
#define	RIGHT_RTDBEDIT_RS   		   7	//启停数据维护
#define	RIGHT_RT_CHANGE     		  39	//主备服务器切换
#define	RIGHT_SCC_CONTROL   		  76	//SCC参数配置
#define	RIGHT_SCC_RUN       		  77	//SCC运行
#define	RIGHT_SE_CONTROL    		  70	//SE参数配置
#define	RIGHT_SE_RUN        		  71	//SE运行
#define	RIGHT_SFM_CHANGE    		  38	//主备前置切换
#define	RIGHT_SFM_CHANNEL   		  37	//通道切换
#define	RIGHT_SFM_CONFIG    		  36	//前置配置
#define	RIGHT_SFM_RS        		   8	//启停前置
#define	RIGHT_SLF_CONTROL   		  82	//SLF参数配置
#define	RIGHT_SLF_DATAEDIT  		  84	//SLF数据修改
#define	RIGHT_SLF_RUN       		  83	//SLF运行
#define	RIGHT_SRS_CONTROL   		  78	//SRS参数配置
#define	RIGHT_SRS_RUN       		  79	//SRS运行
#define	RIGHT_SYSTEM_EVENT  		   2	//系统事件
#define	RIGHT_SYSTEM_RS     		   1	//系统启停
#define	RIGHT_SYS_REDIT     		  68	//远程维护
#define	RIGHT_SYS_TIME      		  67	//系统对时
#define	RIGHT_VVC_CONTROL   		  80	//VVC参数配置
#define	RIGHT_VVC_RUN       		  81	//VVC运行
#define	RIGHT_WINK_OPR      		  89	//停闪操作

#endif // !defined(__SCADA_RIGHT_DEFINE_H_)
